# coding: utf-8

"""
    WebAPI

    Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 

    OpenAPI spec version: <version>
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.block_full import BlockFull
from .models.block_operation import BlockOperation
from .models.block_operation_new import BlockOperationNew
from .models.block_operation_response import BlockOperationResponse
from .models.block_operations_list import BlockOperationsList
from .models.catalog_type import CatalogType
from .models.catalog_types_response import CatalogTypesResponse
from .models.chat_history_response import ChatHistoryResponse
from .models.chat_message import ChatMessage
from .models.chunk import Chunk
from .models.chunk_response import ChunkResponse
from .models.chunks_response import ChunksResponse
from .models.command import Command
from .models.command_call import CommandCall
from .models.command_history_response import CommandHistoryResponse
from .models.command_request import CommandRequest
from .models.command_response import CommandResponse
from .models.command_response_1 import CommandResponse1
from .models.command_result import CommandResult
from .models.commands_response import CommandsResponse
from .models.create_entity_request import CreateEntityRequest
from .models.create_world_request import CreateWorldRequest
from .models.damage_request import DamageRequest
from .models.damage_request_1 import DamageRequest1
from .models.data import Data
from .models.entities_list import EntitiesList
from .models.entity import Entity
from .models.entity_method_result import EntityMethodResult
from .models.entity_response import EntityResponse
from .models.execute_command_response import ExecuteCommandResponse
from .models.execute_player_method_response import ExecutePlayerMethodResponse
from .models.execute_tile_entity_method_response import ExecuteTileEntityMethodResponse
from .models.execute_world_method_response import ExecuteWorldMethodResponse
from .models.husky_crate import HuskyCrate
from .models.husky_crate_full_rewards import HuskyCrateFullRewards
from .models.husky_crate_response import HuskyCrateResponse
from .models.husky_crates_response import HuskyCratesResponse
from .models.inline_response_400 import InlineResponse400
from .models.inventory import Inventory
from .models.item_stack import ItemStack
from .models.location import Location
from .models.login_request import LoginRequest
from .models.login_response import LoginResponse
from .models.mmc_ticket import MMCTicket
from .models.mmc_tickets_ticket_response import MMCTicketsTicketResponse
from .models.mmc_tickets_tickets_response import MMCTicketsTicketsResponse
from .models.mmc_update_ticket_request import MMCUpdateTicketRequest
from .models.message import Message
from .models.message_option import MessageOption
from .models.message_request import MessageRequest
from .models.message_response import MessageResponse
from .models.messages_response import MessagesResponse
from .models.nations_nation import NationsNation
from .models.nations_nation_response import NationsNationResponse
from .models.nations_nations_response import NationsNationsResponse
from .models.nations_rect import NationsRect
from .models.nations_zone import NationsZone
from .models.nucleus_jail_full import NucleusJailFull
from .models.nucleus_jail_response import NucleusJailResponse
from .models.nucleus_jails_response import NucleusJailsResponse
from .models.nucleus_kit import NucleusKit
from .models.nucleus_kit_response import NucleusKitResponse
from .models.nucleus_kits_response import NucleusKitsResponse
from .models.ok import Ok
from .models.player import Player
from .models.player_full_achievements import PlayerFullAchievements
from .models.player_full_armour import PlayerFullArmour
from .models.player_full_connection import PlayerFullConnection
from .models.player_full_experience import PlayerFullExperience
from .models.player_full_food import PlayerFullFood
from .models.player_full_health import PlayerFullHealth
from .models.player_full_joined import PlayerFullJoined
from .models.player_response import PlayerResponse
from .models.players_list import PlayersList
from .models.plugin import Plugin
from .models.plugin_response import PluginResponse
from .models.plugins_response import PluginsResponse
from .models.raw_request import RawRequest
from .models.raw_request_param import RawRequestParam
from .models.raw_response import RawResponse
from .models.server_info import ServerInfo
from .models.server_info_detail import ServerInfoDetail
from .models.servlets_response import ServletsResponse
from .models.single_block import SingleBlock
from .models.tile_entities_response import TileEntitiesResponse
from .models.tile_entity import TileEntity
from .models.tile_entity_response import TileEntityResponse
from .models.update_entity_request import UpdateEntityRequest
from .models.update_player_request import UpdatePlayerRequest
from .models.update_world_request import UpdateWorldRequest
from .models.user import User
from .models.user_response import UserResponse
from .models.vector3 import Vector3
from .models.world import World
from .models.world_full_border import WorldFullBorder
from .models.world_full_dimension import WorldFullDimension
from .models.world_full_dimension_type import WorldFullDimensionType
from .models.world_full_generator import WorldFullGenerator
from .models.world_response import WorldResponse
from .models.worlds_response import WorldsResponse
from .models.block_operation_full import BlockOperationFull
from .models.chunk_full import ChunkFull
from .models.command_full import CommandFull
from .models.entity_full import EntityFull
from .models.husky_crate_full import HuskyCrateFull
from .models.mmc_ticket_full import MMCTicketFull
from .models.message_full import MessageFull
from .models.nations_nation_full import NationsNationFull
from .models.nucleus_kit_full import NucleusKitFull
from .models.player_full import PlayerFull
from .models.plugin_full import PluginFull
from .models.tile_entity_full import TileEntityFull
from .models.world_full import WorldFull

# import apis into sdk package
from .apis.block_api import BlockApi
from .apis.chunk_api import ChunkApi
from .apis.command_api import CommandApi
from .apis.entity_api import EntityApi
from .apis.history_api import HistoryApi
from .apis.husky_crates_api import HuskyCratesApi
from .apis.info_api import InfoApi
from .apis.mmc_tickets_api import MMCTicketsApi
from .apis.message_api import MessageApi
from .apis.nations_api import NationsApi
from .apis.nucleus_api import NucleusApi
from .apis.player_api import PlayerApi
from .apis.plugin_api import PluginApi
from .apis.registry_api import RegistryApi
from .apis.servlet_api import ServletApi
from .apis.tile_entity_api import TileEntityApi
from .apis.user_api import UserApi
from .apis.world_api import WorldApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
