# coding: utf-8

"""
    WebAPI

    Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 

    OpenAPI spec version: <version>
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Inventory(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'stack_count': 'float',
        'item_count': 'float',
        'items': 'list[ItemStack]'
    }

    attribute_map = {
        'name': 'name',
        'stack_count': 'stackCount',
        'item_count': 'itemCount',
        'items': 'items'
    }

    def __init__(self, name=None, stack_count=None, item_count=None, items=None):
        """
        Inventory - a model defined in Swagger
        """

        self._name = None
        self._stack_count = None
        self._item_count = None
        self._items = None

        if name is not None:
          self.name = name
        if stack_count is not None:
          self.stack_count = stack_count
        if item_count is not None:
          self.item_count = item_count
        if items is not None:
          self.items = items

    @property
    def name(self):
        """
        Gets the name of this Inventory.
        The name of the inventory.

        :return: The name of this Inventory.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Inventory.
        The name of the inventory.

        :param name: The name of this Inventory.
        :type: str
        """

        self._name = name

    @property
    def stack_count(self):
        """
        Gets the stack_count of this Inventory.
        The amount of different stacks in the inventory.

        :return: The stack_count of this Inventory.
        :rtype: float
        """
        return self._stack_count

    @stack_count.setter
    def stack_count(self, stack_count):
        """
        Sets the stack_count of this Inventory.
        The amount of different stacks in the inventory.

        :param stack_count: The stack_count of this Inventory.
        :type: float
        """

        self._stack_count = stack_count

    @property
    def item_count(self):
        """
        Gets the item_count of this Inventory.
        The total amount of items in the inventory.

        :return: The item_count of this Inventory.
        :rtype: float
        """
        return self._item_count

    @item_count.setter
    def item_count(self, item_count):
        """
        Sets the item_count of this Inventory.
        The total amount of items in the inventory.

        :param item_count: The item_count of this Inventory.
        :type: float
        """

        self._item_count = item_count

    @property
    def items(self):
        """
        Gets the items of this Inventory.
        The item stacks in the inventory

        :return: The items of this Inventory.
        :rtype: list[ItemStack]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this Inventory.
        The item stacks in the inventory

        :param items: The items of this Inventory.
        :type: list[ItemStack]
        """

        self._items = items

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Inventory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
