# coding: utf-8

"""
    WebAPI

    Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 

    OpenAPI spec version: <version>
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Player(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'uuid': 'str',
        'online': 'bool',
        'location': 'Location',
        'name': 'str',
        'link': 'str',
        '_class': 'str'
    }

    attribute_map = {
        'type': 'type',
        'uuid': 'uuid',
        'online': 'online',
        'location': 'location',
        'name': 'name',
        'link': 'link',
        '_class': 'class'
    }

    def __init__(self, type=None, uuid=None, online=None, location=None, name=None, link=None, _class=None):
        """
        Player - a model defined in Swagger
        """

        self._type = None
        self._uuid = None
        self._online = None
        self._location = None
        self._name = None
        self._link = None
        self.__class = None

        if type is not None:
          self.type = type
        if uuid is not None:
          self.uuid = uuid
        if online is not None:
          self.online = online
        if location is not None:
          self.location = location
        if name is not None:
          self.name = name
        if link is not None:
          self.link = link
        if _class is not None:
          self._class = _class

    @property
    def type(self):
        """
        Gets the type of this Player.
        The type of player, usually `minecraft:player`

        :return: The type of this Player.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Player.
        The type of player, usually `minecraft:player`

        :param type: The type of this Player.
        :type: str
        """

        self._type = type

    @property
    def uuid(self):
        """
        Gets the uuid of this Player.
        The unique identifier of the player.

        :return: The uuid of this Player.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """
        Sets the uuid of this Player.
        The unique identifier of the player.

        :param uuid: The uuid of this Player.
        :type: str
        """

        self._uuid = uuid

    @property
    def online(self):
        """
        Gets the online of this Player.
        True if the player is currently online, false otherwise.

        :return: The online of this Player.
        :rtype: bool
        """
        return self._online

    @online.setter
    def online(self, online):
        """
        Sets the online of this Player.
        True if the player is currently online, false otherwise.

        :param online: The online of this Player.
        :type: bool
        """

        self._online = online

    @property
    def location(self):
        """
        Gets the location of this Player.

        :return: The location of this Player.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """
        Sets the location of this Player.

        :param location: The location of this Player.
        :type: Location
        """

        self._location = location

    @property
    def name(self):
        """
        Gets the name of this Player.
        The name of the player.

        :return: The name of this Player.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Player.
        The name of the player.

        :param name: The name of this Player.
        :type: str
        """

        self._name = name

    @property
    def link(self):
        """
        Gets the link of this Player.
        The API URL which contains detailed information about this player.

        :return: The link of this Player.
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """
        Sets the link of this Player.
        The API URL which contains detailed information about this player.

        :param link: The link of this Player.
        :type: str
        """

        self._link = link

    @property
    def _class(self):
        """
        Gets the _class of this Player.
        The fully qualified class name of the object representing the player. Usually `net.minecraft.entity.player.EntityPlayerMP`.

        :return: The _class of this Player.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """
        Sets the _class of this Player.
        The fully qualified class name of the object representing the player. Usually `net.minecraft.entity.player.EntityPlayerMP`.

        :param _class: The _class of this Player.
        :type: str
        """

        self.__class = _class

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Player):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
