# coding: utf-8

"""
    WebAPI

    Access Sponge powered Minecraft servers through a WebAPI  # Introduction This is the documentation of the various API routes offered by the WebAPI plugin.  This documentation assumes that you are familiar with the basic concepts of Web API's, such as `GET`, `PUT`, `POST` and `DELETE` methods, request `HEADERS` and `RESPONSE CODES` and `JSON` data.  By default this documentation can be found at http:/localhost:8080 (while your minecraft server is running) and the various routes start with http:/localhost:8080/api/...  As a quick test try reaching the route http:/localhost:8080/api/info (remember that you can only access \"localhost\" routes on the server on which you are running minecraft). This route should show you basic information about your server, like the motd and player count.  # Additional data Certain endpoints (such as `/player`, `/entity` and `/tile-entity` have additional properties which are not documented here, because the data depends on the concrete object type (eg. `Sheep` have a wool color, others do not) and on the other plugins/mods that are running on your server which might add additional data.  You can also find more information in the github docs (https:/github.com/Valandur/Web-API/tree/master/docs/DATA.md) 

    OpenAPI spec version: <version>
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PlayerFullAchievements(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        '_class': 'str',
        'description': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        '_class': 'class',
        'description': 'description'
    }

    def __init__(self, id=None, name=None, _class=None, description=None):
        """
        PlayerFullAchievements - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self.__class = None
        self._description = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if _class is not None:
          self._class = _class
        if description is not None:
          self.description = description

    @property
    def id(self):
        """
        Gets the id of this PlayerFullAchievements.
        The unique id of the achievement

        :return: The id of this PlayerFullAchievements.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PlayerFullAchievements.
        The unique id of the achievement

        :param id: The id of this PlayerFullAchievements.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this PlayerFullAchievements.
        The displayed name of the achievement.

        :return: The name of this PlayerFullAchievements.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PlayerFullAchievements.
        The displayed name of the achievement.

        :param name: The name of this PlayerFullAchievements.
        :type: str
        """

        self._name = name

    @property
    def _class(self):
        """
        Gets the _class of this PlayerFullAchievements.
        The fully qualified class name of the achievement.

        :return: The _class of this PlayerFullAchievements.
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """
        Sets the _class of this PlayerFullAchievements.
        The fully qualified class name of the achievement.

        :param _class: The _class of this PlayerFullAchievements.
        :type: str
        """

        self.__class = _class

    @property
    def description(self):
        """
        Gets the description of this PlayerFullAchievements.
        The description that is displayed when hovering the achievement.

        :return: The description of this PlayerFullAchievements.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this PlayerFullAchievements.
        The description that is displayed when hovering the achievement.

        :param description: The description of this PlayerFullAchievements.
        :type: str
        """

        self._description = description

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PlayerFullAchievements):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
